nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
        '^https://www.youtube.com/': # Ajoutez cette ligne pour autoriser YouTube
            allow_origin: ['*']
            allow_methods: ['GET', 'OPTIONS']  # Ajoutez les méthodes nécessaires pour YouTube
            allow_headers: ['Content-Type']    # Ajoutez les en-têtes nécessaires pour YouTube
            max_age: 3600
